version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/
    overwrite: yes
hooks:

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

